# remove commit prefix
git:
  commitPrefix:
    # pattern to match on. E.g. for 'feature/AB-123' to match on the AB-123 use "^\\w+\\/(\\w+-\\w+).*"
    pattern: "^\\w+\\/(\\w+-\\w+).*"

gui: 
  nerdFontsVersion: ""

# nvim default editor
os:
  # Command for editing a file. Should contain "{{filename}}".
  edit: "nvim {{filename}}"

  # Command for editing a file at a given line number. Should contain
  # "{{filename}}", and may optionally contain "{{line}}".
  editAtLine: "nvim +{{line}} {{filename}}"

  # Same as EditAtLine, except that the command needs to wait until the
  # window is closed.
  editAtLineAndWait: "nvim +{{line}} {{filename}}"

# skip confirm "enter to return from lazygit"
promptToReturnFromSubprocess: false 
