# Disable all modules except the ones we need
format = """
$directory\
$git_branch\
$git_status\
$character
"""

[character]
success_symbol = "[>](foreground)"  # This is the default prompt symbol.
error_symbol = "[>](red)"  # This is the default prompt symbol.
vimcmd_symbol = '[<](foreground) '

[directory]
truncate_to_repo = false
style="blue"

[git_branch]
format = '[$branch(:$remote_branch) ](242)'

[git_status]
style = 'white'


